export const inventarioPorMes = [
  {
    "mes": "Diciembre 2025",
    "clientes": [
      {
        "cliente": "Abastos logicos",
        "valor_inventario": null,
        "cajas_inventario": null,
        "costo_promedio": null,
        "ventas_cajas_mes": null,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      },
      {
        "cliente": "CDMX: Arcosa | Fresco | Frigarsa | Canbelt",
        "valor_inventario": null,
        "cajas_inventario": null,
        "costo_promedio": null,
        "ventas_cajas_mes": null,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      },
      {
        "cliente": "Bajo Cero",
        "valor_inventario": null,
        "cajas_inventario": null,
        "costo_promedio": null,
        "ventas_cajas_mes": null,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      },
      {
        "cliente": "Frjalisco",
        "valor_inventario": null,
        "cajas_inventario": null,
        "costo_promedio": null,
        "ventas_cajas_mes": null,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      },
      {
        "cliente": "Alfrimex",
        "valor_inventario": null,
        "cajas_inventario": null,
        "costo_promedio": null,
        "ventas_cajas_mes": null,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      },
      {
        "cliente": "Vulpes",
        "valor_inventario": null,
        "cajas_inventario": null,
        "costo_promedio": null,
        "ventas_cajas_mes": null,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      }
    ],
    "total": {
      "valor_inventario": null,
      "cajas_inventario": null,
      "costo_promedio": null,
      "ventas_cajas_mes": null,
      "llegadas": null,
      "ventas_estimadas": null,
      "inv_mas_llegadas": null,
      "inv_menos_ventas": null,
      "cobertura": null,
      "ultimo_numero": null
    },
    "header_len": 11
  },
  {
    "mes": "Enero 2026",
    "clientes": [
      {
        "cliente": "Abastos logicos",
        "valor_inventario": 2232136.0,
        "cajas_inventario": 7407.0,
        "costo_promedio": 301.0,
        "ventas_cajas_mes": 1803.0,
        "llegadas": 2268.0,
        "ventas_estimadas": 2000.0,
        "inv_mas_llegadas": 9675.0,
        "inv_menos_ventas": 7675.0,
        "cobertura": 3.84,
        "ultimo_numero": 3.84
      },
      {
        "cliente": "CDMX: Arcosa | Fresco | Frigarsa | Canbelt",
        "valor_inventario": 1775097.0,
        "cajas_inventario": 3775.0,
        "costo_promedio": 470.0,
        "ventas_cajas_mes": 1540.0,
        "llegadas": 2268.0,
        "ventas_estimadas": 1200.0,
        "inv_mas_llegadas": 6043.0,
        "inv_menos_ventas": 4843.0,
        "cobertura": 4.04,
        "ultimo_numero": 4.04
      },
      {
        "cliente": "Bajo Cero",
        "valor_inventario": 1544467.0,
        "cajas_inventario": 5539.0,
        "costo_promedio": 279.0,
        "ventas_cajas_mes": 2325.0,
        "llegadas": null,
        "ventas_estimadas": 3200.0,
        "inv_mas_llegadas": 5539.0,
        "inv_menos_ventas": 2339.0,
        "cobertura": 0.73,
        "ultimo_numero": 0.73
      },
      {
        "cliente": "Frjalisco",
        "valor_inventario": 449970.0,
        "cajas_inventario": 1372.0,
        "costo_promedio": 328.0,
        "ventas_cajas_mes": 2613.0,
        "llegadas": null,
        "ventas_estimadas": 2200.0,
        "inv_mas_llegadas": 1372.0,
        "inv_menos_ventas": -828.0,
        "cobertura": -0.38,
        "ultimo_numero": -0.38
      },
      {
        "cliente": "Alfrimex",
        "valor_inventario": 94931.0,
        "cajas_inventario": 356.0,
        "costo_promedio": 267.0,
        "ventas_cajas_mes": 158.0,
        "llegadas": null,
        "ventas_estimadas": 50.0,
        "inv_mas_llegadas": 356.0,
        "inv_menos_ventas": 306.0,
        "cobertura": 6.12,
        "ultimo_numero": 6.12
      },
      {
        "cliente": "Vulpes",
        "valor_inventario": 307923.0,
        "cajas_inventario": 981.0,
        "costo_promedio": 314.0,
        "ventas_cajas_mes": 0.0,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": 981.0,
        "inv_menos_ventas": 981.0,
        "cobertura": null,
        "ultimo_numero": null
      }
    ],
    "total": {
      "valor_inventario": 6404524.73,
      "cajas_inventario": 19429.35,
      "costo_promedio": 326.51,
      "ventas_cajas_mes": 8438.28,
      "llegadas": 4536.0,
      "ventas_estimadas": 8650.0,
      "inv_mas_llegadas": null,
      "inv_menos_ventas": 15315.0,
      "cobertura": 1.77,
      "ultimo_numero": 1.77
    },
    "header_len": 11
  },
  {
    "mes": "Febrero 2026",
    "clientes": [
      {
        "cliente": "Abastos logicos",
        "valor_inventario": 1713755.0,
        "cajas_inventario": 5630.0,
        "costo_promedio": 304.0,
        "ventas_cajas_mes": 1777.0,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      },
      {
        "cliente": "CDMX: Arcosa | Fresco | Frigarsa | Canbelt",
        "valor_inventario": 1961618.0,
        "cajas_inventario": 5823.0,
        "costo_promedio": 337.0,
        "ventas_cajas_mes": 1420.0,
        "llegadas": 2198.0,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      },
      {
        "cliente": "Bajo Cero",
        "valor_inventario": 1677357.0,
        "cajas_inventario": 6005.0,
        "costo_promedio": 279.0,
        "ventas_cajas_mes": 1353.0,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      },
      {
        "cliente": "Frjalisco",
        "valor_inventario": 666909.0,
        "cajas_inventario": 2464.0,
        "costo_promedio": 271.0,
        "ventas_cajas_mes": 1745.0,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      },
      {
        "cliente": "Alfrimex",
        "valor_inventario": 11733.0,
        "cajas_inventario": 44.0,
        "costo_promedio": 267.0,
        "ventas_cajas_mes": 44.0,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      },
      {
        "cliente": "Vulpes",
        "valor_inventario": 177403.0,
        "cajas_inventario": 641.0,
        "costo_promedio": 277.0,
        "ventas_cajas_mes": 0.0,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      }
    ],
    "total": {
      "valor_inventario": 6208773.69,
      "cajas_inventario": 20607.08,
      "costo_promedio": 1734.56,
      "ventas_cajas_mes": 6338.93,
      "llegadas": null,
      "ventas_estimadas": null,
      "inv_mas_llegadas": null,
      "inv_menos_ventas": null,
      "cobertura": null,
      "ultimo_numero": null
    },
    "header_len": 11
  },
  {
    "mes": "Marzo 2026",
    "clientes": [
      {
        "cliente": "Abastos logicos",
        "valor_inventario": 911559.0,
        "cajas_inventario": 2875.0,
        "costo_promedio": 317.0,
        "ventas_cajas_mes": 2765.0,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      },
      {
        "cliente": "CDMX: Arcosa | Fresco | Frigarsa | Canbelt",
        "valor_inventario": 2359652.0,
        "cajas_inventario": 6975.0,
        "costo_promedio": 338.0,
        "ventas_cajas_mes": 1722.0,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      },
      {
        "cliente": "Bajo Cero",
        "valor_inventario": 1401515.0,
        "cajas_inventario": 4955.0,
        "costo_promedio": 283.0,
        "ventas_cajas_mes": 1424.0,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      },
      {
        "cliente": "Frjalisco",
        "valor_inventario": 1084784.0,
        "cajas_inventario": 3930.0,
        "costo_promedio": 276.0,
        "ventas_cajas_mes": 2227.0,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      },
      {
        "cliente": "Alfrimex",
        "valor_inventario": null,
        "cajas_inventario": null,
        "costo_promedio": null,
        "ventas_cajas_mes": null,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      },
      {
        "cliente": "Vulpes",
        "valor_inventario": 649083.0,
        "cajas_inventario": 2433.0,
        "costo_promedio": 267.0,
        "ventas_cajas_mes": null,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": null,
        "inv_menos_ventas": null,
        "cobertura": null,
        "ultimo_numero": null
      }
    ],
    "total": {
      "valor_inventario": 6406593.39,
      "cajas_inventario": 21168.28,
      "costo_promedio": null,
      "ventas_cajas_mes": 8137.83,
      "llegadas": null,
      "ventas_estimadas": null,
      "inv_mas_llegadas": null,
      "inv_menos_ventas": null,
      "cobertura": null,
      "ultimo_numero": null
    },
    "header_len": 11
  },
  {
    "mes": "Abril 2026",
    "clientes": [
      {
        "cliente": "Abastos logicos",
        "valor_inventario": 869368.0,
        "cajas_inventario": 3176.0,
        "costo_promedio": 274.0,
        "ventas_cajas_mes": 2058.0,
        "llegadas": 4644.0,
        "ventas_estimadas": 2284.06,
        "inv_mas_llegadas": 7820.25,
        "inv_menos_ventas": 5536.19,
        "cobertura": 2.42,
        "ultimo_numero": 2.42
      },
      {
        "cliente": "CDMX: Arcosa | Fresco | Frigarsa | Canbelt",
        "valor_inventario": 2102810.0,
        "cajas_inventario": 6096.0,
        "costo_promedio": 345.0,
        "ventas_cajas_mes": 1756.0,
        "llegadas": 1476.0,
        "ventas_estimadas": 1200.0,
        "inv_mas_llegadas": 7571.8,
        "inv_menos_ventas": 6371.8,
        "cobertura": 5.31,
        "ultimo_numero": 5.31
      },
      {
        "cliente": "Bajo Cero",
        "valor_inventario": 1376960.0,
        "cajas_inventario": 4971.0,
        "costo_promedio": 277.0,
        "ventas_cajas_mes": 2477.0,
        "llegadas": 720.0,
        "ventas_estimadas": 1000.0,
        "inv_mas_llegadas": 7625.79,
        "inv_menos_ventas": 6625.79,
        "cobertura": 6.63,
        "ultimo_numero": 6.63
      },
      {
        "cliente": "Vulpes",
        "valor_inventario": 529960.0,
        "cajas_inventario": 1935.0,
        "costo_promedio": 274.0,
        "ventas_cajas_mes": null,
        "llegadas": 0.0,
        "ventas_estimadas": 0.0,
        "inv_mas_llegadas": 0.0,
        "inv_menos_ventas": 0.0,
        "cobertura": null,
        "ultimo_numero": null
      },
      {
        "cliente": "Frjalisco",
        "valor_inventario": 1231168.0,
        "cajas_inventario": 4584.0,
        "costo_promedio": 269.0,
        "ventas_cajas_mes": 3410.0,
        "llegadas": 1185.0,
        "ventas_estimadas": 2800.0,
        "inv_mas_llegadas": 5769.0,
        "inv_menos_ventas": 2969.0,
        "cobertura": 1.06,
        "ultimo_numero": 1.06
      },
      {
        "cliente": "Alfrimex",
        "valor_inventario": null,
        "cajas_inventario": null,
        "costo_promedio": null,
        "ventas_cajas_mes": null,
        "llegadas": null,
        "ventas_estimadas": null,
        "inv_mas_llegadas": 0.0,
        "inv_menos_ventas": 0.0,
        "cobertura": null,
        "ultimo_numero": null
      }
    ],
    "total": {
      "valor_inventario": 6110265.49,
      "cajas_inventario": 20761.84,
      "costo_promedio": null,
      "ventas_cajas_mes": 9701.44,
      "llegadas": 8025.0,
      "ventas_estimadas": 7284.0,
      "inv_mas_llegadas": 28787.0,
      "inv_menos_ventas": 21503.0,
      "cobertura": null,
      "ultimo_numero": null
    },
    "header_len": 11
  },
  {
    "mes": "Mayo 2026",
    "clientes": [
      {
        "cliente": "Abastos logicos",
        "valor_inventario": 743039.0,
        "cajas_inventario": 2692.0,
        "costo_promedio": 276.0,
        "ventas_cajas_mes": 493.0,
        "llegadas": 4644.0,
        "ventas_estimadas": 2000.0,
        "inv_mas_llegadas": 7336.0,
        "inv_menos_ventas": 5336.0,
        "cobertura": 2.67,
        "ultimo_numero": 2.67
      },
      {
        "cliente": "CDMX: Arcosa | Fresco | Frigarsa | Canbelt",
        "valor_inventario": 2089695.0,
        "cajas_inventario": 5626.0,
        "costo_promedio": 371.0,
        "ventas_cajas_mes": 411.0,
        "llegadas": 3024.0,
        "ventas_estimadas": 1200.0,
        "inv_mas_llegadas": 8649.8,
        "inv_menos_ventas": 7449.8,
        "cobertura": 6.21,
        "ultimo_numero": 6.21
      },
      {
        "cliente": "Bajo Cero",
        "valor_inventario": 1358076.0,
        "cajas_inventario": 4926.0,
        "costo_promedio": 276.0,
        "ventas_cajas_mes": 0.0,
        "llegadas": 2622.0,
        "ventas_estimadas": 1000.0,
        "inv_mas_llegadas": 8933.79,
        "inv_menos_ventas": 7933.79,
        "cobertura": 7.93,
        "ultimo_numero": 7.93
      }
    ],
    "total": {},
    "header_len": 11
  }
];